title: User
modelClass: TinTrang\Tuser\Models\User
list: $/tintrang/tuser/models/user/columns.yaml
recordUrl: 'tintrang/tuser/user/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
